// Generated by scripts/download-plant-photos.mjs — do not edit by hand.
// Photos: iNaturalist observers, CC0 / CC BY / CC BY-SA. See scripts/plant-photos.json.
import type { PlantImage } from './plantImageTypes';

export const PLANT_IMAGES: Record<string, PlantImage[]> = {};
