// Generated by scripts/fetch-plant-images.mjs — do not edit by hand.
// Run `npm run fetch-images` to download openly licensed photos into assets/plants/.
import type { PlantImage } from './plantImageTypes';

export const PLANT_IMAGES: Record<string, PlantImage> = {};
